FROM arm32v6/alpine:latest
MAINTAINER David McElin
COPY qemu-arm-static /usr/bin/
RUN apk add openjdk8-jre-base
WORKDIR /repo/Minecraft
ENTRYPOINT ["java", "-Xmx1024M", "-Xms1024M", "-jar", "/repo/Minecraft/server.1.13.2.jar", "nogui"]
