FROM arm32v6/alpine:latest
MAINTAINER David McElin
COPY qemu-arm-static /usr/bin/
RUN apk add openjdk8-jre-base
WORKDIR /repo/Minecraft
ENTRYPOINT ["java", "-Xmx512M", "-Xms511M", "-jar", "/repo/Minecraft/server.1.13.2.jar"]
